### ISSUE TITLE
Languages with dependent types

### ISSUE THREAD

**Issue by pvdrz** [FLAGlab/bounded-const-generics-rust#1]
Ver que otras implementaciones de _dependent types_ existen. Por el momento sabemos que los siguientes lenguajes los incluyen:
- [x] [Haskell](https://cs.brynmawr.edu/~rae/papers/2016/thesis/eisenberg-thesis.pdf)
- [x] [Idris](https://www.idris-lang.org/)
- [ ] [Cayenne](http://citeseer.ist.psu.edu/viewdoc/summary?doi=10.1.1.47.155) (recomendado por la comunidad)
- [ ] [Coq](https://coq.inria.fr/)
- [ ] [Agda](https://github.com/agda/agda)
- [ ] [F*](https://www.fstar-lang.org/)
